all:
	$(MAKE) -C null_deref 
	$(MAKE) -C buff_overflow 
	$(MAKE) -C simple_branch
	$(MAKE) -C injection_demo

clean:
	$(MAKE) -C null_deref clean
	$(MAKE) -C buff_overflow clean
	$(MAKE) -C simple_branch clean
	$(MAKE) -C injection_demo clean
