name: tests

on:
  workflow_dispatch:
  push:
    branches: 
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build .#tests
      - run: mkdir cozy-traces
      - run: cp result/*.json cozy-traces
      - uses: actions/upload-artifact@v4
        with:
          name: cozy-traces
          path: cozy-traces/
